# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  # manual workflow run
  workflow_dispatch:

  push:
    branches: ["master"]

jobs:
  build:

    runs-on: macos-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: jpackage --name GithubNotifier --input ./target --main-jar GithubNotificationsApp-1.0-SNAPSHOT-jar-with-dependencies.jar --icon src/main/resources/icon.icns  --mac-package-name "Github Notifier"  --description "Notifies you about new PRs in the watched repos" --vendor "ash852006@gmail.com"  --copyright "Copyleft (L)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release-macosx-${{ github.ref }}
        body: |
          Mac OS X
        draft: false
        prerelease: false
          
    - uses: AButler/upload-release-assets@v2.0
      name: Create Release
      with:
        files: 'GithubNotifier-1.0.dmg'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}

